Repository kubernetes-csi/csi-release-tools, pull requests merged in 2019-07, with the labels that each got.

#20 more flexible test driver config
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#21 Add 1.15 jobs
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note, size/L

#22 prow.sh: tag master images with a large version number
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note, size/XS
