Repository kubernetes-csi/csi-release-tools, pull requests merged in 2019-04, with the labels that each got.

#11 verify shellcheck
  README.md
  build.make
  util.sh
  verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#13 prow enhancements
  build.make
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#14 prow.sh: remove AllAlpha=all, part II
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#15 build.make: Replace 'return' to 'exit' to fix shellcheck error
  build.make
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#16 prow.sh: update csi-driver-host-path
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#17 prow.sh: skip sanity testing if component doesn't support it
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#18 update to Go 1.12.4
  travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS
