Repository kubernetes-csi/csi-release-tools, pull requests merged in 2019-12, with the labels that each got.

#50 Use kind v0.6.0
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#51 Enable topology testing with hostpath driver
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#49 Improve snapshot-controller running check and version_gt to support multiple formats
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#53 fix syntax for ppc64le build
  build.make
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#52 Improve README by adding an explicit Kubernetes dependency section
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#56 Enable snapshot tests in 1.17 to be run in non-alpha jobs.
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#57 Fix version_gt to work with Kubernetes prefix
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
