Repository kubernetes-csi/csi-release-tools, pull requests merged in 2019-11, with the labels that each got.

#42 prow.sh: use vendor directory if available
  build.make
  prow.sh
  travis.yml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#43 prow.sh: also log output of system containers
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#46 delete kind cluster after tests run
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#45 Add snapshotter CRDs after cluster setup
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note, size/M

#47 Adding build for ppc64le
  build.make
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note, size/XS
