Repository kubernetes-csi/csi-release-tools, pull requests merged in 2019-10, with the labels that each got.

#35 Build Windows only for amd64
  build.make
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#34 update Go mod support
  README.md
  build.make
  go-get-kubernetes.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L

#36 Do full git clones in travis
  travis.yml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#40 Add new variables for 1.16 and remove 1.13
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#41 Go version 1.13, helper scripts
  build.make
  travis.yml
  update-vendor.sh
  verify-go-version.sh
  verify-vendor.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/L
