Repository kubernetes-csi/csi-release-tools, pull requests merged in 2020-06, with the labels that each got.

#88 multiarch windows fix
  build.make
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#89 cloud build: initialize support for running commands in Dockerfile
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#90 cloud build: k8s-staging-sig-storage
  cloudbuild.yaml
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#91 prow.sh: enable building arm64 image
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#92 filter-junit: Fix golint error
  filter-junit.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#93 filter-junit: Fix gofmt error
  filter-junit.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, release-note-none, size/XS
