Repository kubernetes-csi/csi-release-tools, pull requests merged in 2020-01, with the labels that each got.

#60 Update prow hostpath driver version to 1.3.0-rc2
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#61 Fix overriding of junit results
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#64 Update snapshotter to version v2.0.0
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#65 Update hostpath driver version to get fix for connection-timeout
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#54 Document the process for releasing a new sidecar
  SIDECAR_RELEASE_PROCESS.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#67 fix incorrect link
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS
