Repository kubernetes-csi/csi-release-tools, pull requests merged in 2020-10, with the labels that each got.

#99 Update release process
  SIDECAR_RELEASE_PROCESS.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#106 Only set staging registry when running canary job
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#104 Update to snapshot-controller v3.0.0
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#107 prow.sh: update to kind 0.9, support Kubernetes 1.19
  prow.sh
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, release-note, size/L

#108 Add go ldflags using LDFLAGS at the time of compilation
  build.make
Labels: approved, cncf-cla: yes, kind/bug, lgtm, ok-to-test, release-note, size/XS

#110 prow.sh: work around "kind build node-image" failure
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#109 prow.sh: only run alpha tests for latest Kubernetes release
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
