Repository kubernetes-csi/csi-release-tools, pull requests merged in 2021-05, with the labels that each got.

#146 Kubernetes 1.21
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#147 Mock testing
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#148 prow.sh: enable -csi.checkpathcmd option in csi-sanity
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/S

#151 Replace `which` command ( non standard) with `command -v` builtin
  verify-shellcheck.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#150 Add parameter base_image and addon_image to BUILD_PLATFORMS
  build.make
  cloudbuild.yaml
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#152 prow.sh: use csi-test v4.2.0
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#153 build.make: fix image publishng
  build.make
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#155 owners: introduce aliases
  KUBERNETES_CSI_OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#149 prow.sh: collect cluster logs
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#157 Adding myself to csi reviewers group
  KUBERNETES_CSI_OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#158 prow.sh: more flexible CSI_PROW_DEPLOYMENT
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#159 prow.sh: more flexible CSI_PROW_DEPLOYMENT, part II
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/M

#160 prow.sh: update to KinD v0.11.0
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#161 prow.sh: fix mock testing
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#163 prow.sh: remove Bazel build support
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#162 prow.sh: allow shell commands in CSI_PROW_SANITY_POD
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S
