Repository kubernetes-csi/csi-release-tools, pull requests merged in 2021-02, with the labels that each got.

#133 prow.sh: fix "on-master" prow jobs
  prow.sh
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS

#132 fix: default boilerplate path
  boilerplate/boilerplate.py
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, release-note-none, size/XS

#129 README.md: document usage of --squash
  README.md
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/S

#134 add build-arg ARCH
  build.make
Labels: approved, cncf-cla: yes, lgtm, release-note-none, size/XS
