Repository kubernetes-csi/csi-release-tools, pull requests merged in 2022-02, with the labels that each got.

#185 Fix OWNERS files with allowed keywords
  KUBERNETES_CSI_OWNERS_ALIASES
Labels: ok-to-test, release-note-none, size/S, cncf-cla: yes, lgtm, approved

#188 SIDECAR_RELEASE_PROCESS.md: Update release-notes syntax
  SIDECAR_RELEASE_PROCESS.md
Labels: ok-to-test, release-note-none, cncf-cla: yes, kind/documentation, lgtm, approved, size/M

#187 Remove Windows versions 1909 and 2004 which have reached EOL
  prow.sh
Labels: size/XS, release-note-none, cncf-cla: yes, lgtm, approved
