Repository kubernetes-csi/csi-release-tools, pull requests merged in 2022-06, with the labels that each got.

#194 Move from k8s.gcr.io to registry.k8s.io
  prow.sh
Labels: size/XS, release-note-none, needs-ok-to-test, cncf-cla: yes, lgtm, approved

#195 fix testing with latest Kubernetes
  prow.sh
Labels: release-note-none, size/S, cncf-cla: yes, lgtm, approved

#196 introduce control variable for non alpha feature gate configuration
  prow.sh
Labels: size/XS, release-note, cncf-cla: yes, lgtm, approved

#192 fix boilerplate header
  go-get-kubernetes.sh
Labels: size/XS, release-note-none, cncf-cla: yes, lgtm, approved
