Repository kubernetes-csi/csi-release-tools, pull requests merged in 2023-08, with the labels that each got.

#228 chore: adopt kubernetes recommand label
  prow.sh
Labels: ok-to-test, release-note, size/S, cncf-cla: yes, lgtm, approved

#231 Update cloudbuild image with go 1.20.5
  cloudbuild.yaml
Labels: size/XS, release-note-none, cncf-cla: yes, lgtm, approved

#219 Update registry k8s.gcr.io -> registry.k8s.io
  SIDECAR_RELEASE_PROCESS.md
  cloudbuild.yaml
Labels: ok-to-test, size/XS, release-note-none, lifecycle/rotten, cncf-cla: yes, lgtm, approved

#229 fixing some codespell errors
  contrib/get_supported_version_csi-sidecar.py
Labels: ok-to-test, size/XS, release-note-none, cncf-cla: yes, lgtm, approved

#233 remove windows 20H2 build since it's EOL long time ago
  prow.sh
Labels: size/XS, release-note, cncf-cla: yes, lgtm, approved

#234 fixed broken links of testgrid dashboard
  SIDECAR_RELEASE_PROCESS.md
Labels: ok-to-test, release-note-none, size/S, cncf-cla: yes, kind/documentation, lgtm, approved
