Repository kubernetes-csi/csi-release-tools, pull requests merged in 2023-11, with the labels that each got.

#243 pull-test.sh: avoid "git subtree pull" error
  pull-test.sh
Labels: size/XS, release-note-none, cncf-cla: yes, lgtm, approved

#240 Update go version to 1.21 to match k/k
  prow.sh
Labels: size/XS, release-note, cncf-cla: yes, lgtm, approved

#237 Add script to generate patch release notes
  SIDECAR_RELEASE_PROCESS.md
  generate_patch_release_notes.sh
Labels: release-note-none, cncf-cla: yes, lgtm, size/L, approved
