Repository kubernetes-csi/csi-release-tools, pull requests merged in 2024-05, with the labels that each got.

#251 Add test-logcheck target
  build.make
  verify-logcheck.sh
Labels: release-note, cncf-cla: yes, lgtm, approved, size/M

#253 Fix typo
  verify-logcheck.sh
Labels: size/XS, release-note-none, cncf-cla: yes, lgtm, approved

#252 Update go to 1.22.3
  prow.sh
Labels: size/XS, release-note, cncf-cla: yes, lgtm, approved

#254 Add GitHub Actions workflows
  .github/dependabot.yaml
  .github/workflows/codespell.yml
  .github/workflows/trivy.yaml
Labels: release-note-none, cncf-cla: yes, lgtm, approved, size/M

#255 fix typo in sidecar release process
  SIDECAR_RELEASE_PROCESS.md
Labels: size/XS, release-note-none, cncf-cla: yes, lgtm, approved
