Repository kubernetes-csi/csi-release-tools, pull requests merged in 2024-12, with the labels that each got.

#262 use new GOTOOLCHAIN env to manage go version
  prow.sh
Labels: ok-to-test, release-note, size/S, cncf-cla: yes, lgtm, approved

#259 Remove --kube-root deprecated kind argument
  prow.sh
Labels: ok-to-test, kind/cleanup, size/XS, release-note-none, cncf-cla: yes, lgtm, approved

#260 chore: update CSI driver version to 1.15
  prow.sh
Labels: ok-to-test, size/XS, release-note-none, cncf-cla: yes, lgtm, approved

#267 Set GOMODCACHE to avoid re-download toolchain
  prow.sh
Labels: ok-to-test, size/XS, release-note-none, cncf-cla: yes, lgtm, approved

#266 Bump csi-sanity to 5.3.1
  prow.sh
Labels: size/XS, release-note-none, cncf-cla: yes, lgtm, approved

#268 Update cloudbuild image with go 1.21+
  cloudbuild.yaml
Labels: ok-to-test, size/XS, release-note-none, cncf-cla: yes, lgtm, approved
